# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create RG and web app
      run: |
        az group create -n gh-demo -l westus2
        az appservice plan create -g gh-demo -n gh-demo-plan --sku S1
        az webapp create -g gh-demo -p gh-demo-plan -n gh-demo-app
        az webapp deployment slot create -g gh-demo -n gh-demo-app -s staging
    
    - run: |
        echo ${{ github.ref }}
        echo ::set-env name=SLOTNAME::"production"
    
    - name: Deploy code to staging slot
      uses: Azure/webapps-deploy@v2
      with:
        app-name: gh-demo-app
        slot-name: ${{ env.SLOTNAME }}
